apiVersion: v1
kind: Service
metadata:
  namespace: swtdisp-ap1-gr10
  name: swtdisp-grp10-heat-submission-service
  labels:
    app: swtdisp-grp10-heat-submission-service
    
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: heat-submission-service-pod