apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: swtdisp-ap1-gr10
  name: swtdisp-grp10-iot-heat-metering-unit
  labels:
    app: swtdisp-grp10-iot-heat-metering-unit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-heat-metering-unit-pod
  
  template:
    metadata:
      name: iot-heat-metering-unit-pod
      labels:
        app: iot-heat-metering-unit-pod
    spec:
      containers:
        - name: swtdisp-grp10-iot-heat-metering-unit-container
          image: mark2830/iot_heat_metering_unit
          ports:
            - containerPort: 80 