version: '3.4'

services:
  tecais.iot.heatmeteringunit:
    container_name: iot_heat_metering_unit
    image: elgaard1/iot_heat_metering_unit89
    networks:
      - disp
    build:
      context: .
      dockerfile: TECAIS.IOT.HeatMeteringUnit/Dockerfile
    ports:
      - 9000:80
      - 44366:80
    restart: always
networks:
  disp:
    external: 
      name: disp